### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by meudnaes** [ITA-Solar/BifrostTools.jl#6]
Some points to make the code more julianic

- Right now, a lot of the functions have the prefix `br_`. I suggest that we remove this for better readability. There is also a point to avoid abbreviations in julia.
- Snake case for functions, and don't abbreviate. This is relevant for e.g. the stagger operations. The function `br_xdn`would become something like `x_down`
- Camel case for all structs. The only struct not following this convention is the `EOS_tables`

**Comment by eilifso** [comment]
I agree.

**Comment by borisvg** [comment]
I agree partially. I have no problem in skipping the br_ prefix. I do agree with changing to x_down. These functions are supposed to mirror the fortran xdn procedures and the IDL xdn functions. Changing the names would not be smart in my oppoinion. History has power

B

Den 18. jan. 2024 kl. 14.53 skrev Eilif Sommer Øyre ***@***.***>:

﻿

I agree.

**Comment by matsca** [comment]
I agree with Boris that history has some interest. When Julia routines are functionally identical to Fortran, IDL or Python routines it would be good to see that also from the name. br_ prefix is important in IDL because of a global name-space but can be skipped in other languages.

Best regards,

Mats




On 18 Jan 2024, at 11:19, Elias Udnæs ***@***.***> wrote:



Some points to make the code more julianic

  *   Right now, a lot of the functions have the prefix br_. I suggest that we remove this for better readability. There is also a point to avoid abbreviations in julia.
  *   Snake case for functions, and don't abbreviate. This is relevant for e.g. the stagger operations. The function br_xdnwould become something like x_down
  *   Camel case for all structs. The only struct not following this convention is the EOS_tables

**Comment by meudnaes** [comment]
I agree with your points. We will remove the prefix, and try to keep the function names as close to the fortran routines as possible.
